version: "2"

run:
  timeout: 5m
  go: "1.24"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - gosec
    - bodyclose
    - noctx

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/alexmorbo/keep-mattermost-bridge

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
